- tools/qgepmaptooladdfeature.py
see issue: https://github.com/QGEP/QGEP/issues/406
Adding reaches: snap to other layers and snap to Z
snapping indicators remain to be done
> adding reaches: keep Z  + snapping indicators

- src/tools/qgepnetwork.py
Fix https://github.com/QGEP/QGEP/issues/444
> Missing update to QGIS 3

- src/tools/qgepnetwork.py
- src/utils/qt_utils.py
the old approach using external dependencies with QtSql was broken
> Use QgsTransaction to refresh network topology

- src/processing_provider/change_reach_direction.py
> Mark edit buffer dirty after changing reach direction

- src/processing_provider/snap_reach.py
Fix https://github.com/QGEP/QGEP/issues/481
> Update snap reach algorithm to QGIS 3

- src/tools/qgepnetwork.py
Fix https://github.com/QGEP/qgepplugin/issues/33
> Do not raise exception on null geometries

- src/gui/forms.py
- src/tools/qgepmaptooladdfeature.py
References https://github.com/QGEP/QGEP/issues/454
> Fix digitize wastewater structure geometry

- src/tools/qgepmaptools.py
References https://github.com/QGEP/QGEP/issues/443
> Prioritize nodes over reaches when snapping

- src/tools/qgepmaptools.py
Please forgive me that I have connected rp_from and rp_to to the same wastewater node. Won't do it again!
References QGEP/QGEP#443
> Only allow to connect RP_TO to reaches

- src/tools/qgepmaptooladdfeature.py
> Update QgsAttributeForm to API 3

- qgepplugin/tools/qgepmaptools.py
- qgepplugin/tools/qgepprofile.py
Fix https://github.com/QGEP/QGEP/issues/464
Fix https://github.com/QGEP/QGEP/issues/460
> fix #464 : fix glitch in profile when entering points one by one

- qgepplugin/qgepplugin.py
- qgepplugin/tools/qgepmaptools.py
Some small improvements that don't deserve a pull request for each.
So far :
- better support for PluginReloader (log handler was registered multiple times and layers were only loaded on project loading, not on plugin initialisation)
- duplicated line
> Small improvements

- qgepplugin/processing_provider/provider.py
To solve https://github.com/QGEP/QGEP/issues/543
> remove default swmm path

- qgepplugin/tools/qgepmaptooladdfeature.py
> fix #596 where snapping to point layer failed

- qgepplugin/processing_provider/QgepSwmm.py
- qgepplugin/processing_provider/swmm_create_input.py
- qgepplugin/processing_provider/swmm_execute.py
- qgepplugin/processing_provider/swmm_extract_results.py
Add the possibility to choose if the current or planned state must be exported. 
Linked to this update of the datamodel: https://github.com/QGEP/datamodel/pull/163/
Fixes QGEP/QGEP#559
> Qgep swmm states

- qgepplugin/utils/translation.py
fixes https://github.com/QGEP/QGEP/issues/618
> translations don't load

- qgepplugin/tools/qgepmaptooladdfeature.py
see https://github.com/QGEP/QGEP/issues/635
> fix #365 : wizard creates null geometry for raches on QGIS 3.16

- qgepplugin/gui/qgepdatamodeldialog.py
minor UI bug-fixes on datamodel tool
> Fix devmode datamodeltool

- qgepplugin/qgepplugin.py
This improves the way postgres connection settings are retrieved from the layer (support for cases where they do not use pgservice).
Hopefully fixes https://github.com/QGEP/QGEP/issues/725
Depends on https://github.com/QGEP/qgepqwat2ili/pull/97 that should be merged first.
> improve parsing of pg connection settings from layer

- qgepplugin/gui/qgepdatamodeldialog.py
minor improvements of the datamodel tool to better handle missing/misconfigured pgservice file
> [datamodel tool]pgconf related gui fixes

- .github/workflows/plugin-package.yml
Create plugin package workflow
> Create plugin package workflow

- .github/workflows/plugin-package.yml
No validation for package version
> No validation for package version
